// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CodeServiceClient is the client API for CodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CodeServiceClient interface {
	GetCodeByEmail(ctx context.Context, in *GetCodeByEmailRequest, opts ...grpc.CallOption) (*GetCodeByEmailResponse, error)
	CreateCodeByEmail(ctx context.Context, in *CreateCodeByEmailRequest, opts ...grpc.CallOption) (*CreateCodeByEmailResponse, error)
}

type codeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCodeServiceClient(cc grpc.ClientConnInterface) CodeServiceClient {
	return &codeServiceClient{cc}
}

func (c *codeServiceClient) GetCodeByEmail(ctx context.Context, in *GetCodeByEmailRequest, opts ...grpc.CallOption) (*GetCodeByEmailResponse, error) {
	out := new(GetCodeByEmailResponse)
	err := c.cc.Invoke(ctx, "/durudex.CodeService/GetCodeByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codeServiceClient) CreateCodeByEmail(ctx context.Context, in *CreateCodeByEmailRequest, opts ...grpc.CallOption) (*CreateCodeByEmailResponse, error) {
	out := new(CreateCodeByEmailResponse)
	err := c.cc.Invoke(ctx, "/durudex.CodeService/CreateCodeByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CodeServiceServer is the server API for CodeService service.
// All implementations must embed UnimplementedCodeServiceServer
// for forward compatibility
type CodeServiceServer interface {
	GetCodeByEmail(context.Context, *GetCodeByEmailRequest) (*GetCodeByEmailResponse, error)
	CreateCodeByEmail(context.Context, *CreateCodeByEmailRequest) (*CreateCodeByEmailResponse, error)
	mustEmbedUnimplementedCodeServiceServer()
}

// UnimplementedCodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCodeServiceServer struct {
}

func (UnimplementedCodeServiceServer) GetCodeByEmail(context.Context, *GetCodeByEmailRequest) (*GetCodeByEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCodeByEmail not implemented")
}
func (UnimplementedCodeServiceServer) CreateCodeByEmail(context.Context, *CreateCodeByEmailRequest) (*CreateCodeByEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCodeByEmail not implemented")
}
func (UnimplementedCodeServiceServer) mustEmbedUnimplementedCodeServiceServer() {}

// UnsafeCodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CodeServiceServer will
// result in compilation errors.
type UnsafeCodeServiceServer interface {
	mustEmbedUnimplementedCodeServiceServer()
}

func RegisterCodeServiceServer(s grpc.ServiceRegistrar, srv CodeServiceServer) {
	s.RegisterService(&CodeService_ServiceDesc, srv)
}

func _CodeService_GetCodeByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCodeByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeServiceServer).GetCodeByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/durudex.CodeService/GetCodeByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeServiceServer).GetCodeByEmail(ctx, req.(*GetCodeByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodeService_CreateCodeByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCodeByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeServiceServer).CreateCodeByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/durudex.CodeService/CreateCodeByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeServiceServer).CreateCodeByEmail(ctx, req.(*CreateCodeByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CodeService_ServiceDesc is the grpc.ServiceDesc for CodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "durudex.CodeService",
	HandlerType: (*CodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCodeByEmail",
			Handler:    _CodeService_GetCodeByEmail_Handler,
		},
		{
			MethodName: "CreateCodeByEmail",
			Handler:    _CodeService_CreateCodeByEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/delivery/grpc/pb/code.proto",
}
