// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type RefreshTokens struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokensInput struct {
	RefreshToken string `json:"refreshToken"`
}

type SignIn struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type SignInInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type SignUp struct {
	ID uint64 `json:"id"`
}

type SignUpInput struct {
	Username string    `json:"username"`
	Name     string    `json:"name"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
	Birthday time.Time `json:"birthday"`
	Sex      int32     `json:"sex"`
}
